
type MapStyleConfig = {
  mbtilesUrl: string;
};

export function createMapStyle({ mbtilesUrl }: MapStyleConfig) {
  return {
    version: 8,
    name: 'Cyprus offline',
    sources: {
      openmaptiles: {
        type: 'vector',
        url: mbtilesUrl,
      },
    },
    glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
    layers: [
      {
        id: 'background',
        type: 'background',
        paint: {
          'background-color': '#f2efe9',
        },
      },
      {
        id: 'water',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'water',
        paint: {
          'fill-color': '#b5d0d0',
          'fill-opacity': 1,
        },
      },
      {
        id: 'waterway',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'waterway',
        minzoom: 8,
        paint: {
          'line-color': '#b5d0d0',
          'line-width': [
            'interpolate',
            ['linear'],
            ['zoom'],
            8,
            0.5,
            12,
            1,
            16,
            2,
          ],
        },
      },
      {
        id: 'landuse-residential',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landuse',
        filter: ['==', 'class', 'residential'],
        paint: {
          'fill-color': '#e8e4e0',
          'fill-opacity': 0.6,
        },
      },
      {
        id: 'landuse-commercial',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'landuse',
        filter: ['in', 'class', 'commercial', 'industrial'],
        paint: {
          'fill-color': '#f5ebe0',
          'fill-opacity': 0.5,
        },
      },
      {
        id: 'park',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'park',
        paint: {
          'fill-color': '#d4edda',
          'fill-opacity': 0.7,
        },
      },
      {
        id: 'building',
        type: 'fill',
        source: 'openmaptiles',
        'source-layer': 'building',
        minzoom: 15,
        paint: {
          'fill-color': '#e0ddd5',
          'fill-opacity': [
            'interpolate',
            ['linear'],
            ['zoom'],
            15,
            0.4,
            16,
            0.7,
            18,
            0.9,
          ],
          'fill-outline-color': '#d0cdc5',
        },
      },
      {
        id: 'road-path',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'path', 'track'],
        minzoom: 14,
        paint: {
          'line-color': '#d4d4d4',
          'line-width': [
            'interpolate',
            ['linear'],
            ['zoom'],
            14,
            0.5,
            16,
            1,
            18,
            1.5,
          ],
          'line-dasharray': [2, 1],
        },
      },
      {
        id: 'road-minor',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'minor', 'service'],
        minzoom: 13,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#ffffff',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            13,
            0.5,
            14,
            1,
            16,
            2,
            18,
            3,
          ],
        },
      },
      {
        id: 'road-minor-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'minor', 'service'],
        minzoom: 13,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#cfcdca',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            13,
            1,
            14,
            2,
            16,
            3.5,
            18,
            5,
          ],
          'line-gap-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            13,
            0.5,
            14,
            1,
            16,
            2,
            18,
            3,
          ],
        },
      },
      {
        id: 'road-secondary-tertiary',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'secondary', 'tertiary'],
        minzoom: 11,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#ffffff',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            11,
            0.5,
            13,
            1.5,
            16,
            3,
            18,
            5,
          ],
        },
      },
      {
        id: 'road-secondary-tertiary-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['in', 'class', 'secondary', 'tertiary'],
        minzoom: 11,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#c5c3c0',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            11,
            1,
            13,
            2.5,
            16,
            5,
            18,
            7.5,
          ],
          'line-gap-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            11,
            0.5,
            13,
            1.5,
            16,
            3,
            18,
            5,
          ],
        },
      },
      {
        id: 'road-primary',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'primary'],
        minzoom: 9,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#ffffff',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            9,
            0.5,
            12,
            2,
            16,
            4,
            18,
            6,
          ],
        },
      },
      {
        id: 'road-primary-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'primary'],
        minzoom: 9,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#b8b6b3',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            9,
            1,
            12,
            3,
            16,
            6,
            18,
            9,
          ],
          'line-gap-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            9,
            0.5,
            12,
            2,
            16,
            4,
            18,
            6,
          ],
        },
      },
      {
        id: 'road-trunk',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'trunk'],
        minzoom: 8,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#fdf8d4',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            8,
            0.5,
            12,
            2.5,
            16,
            5,
            18,
            7,
          ],
        },
      },
      {
        id: 'road-trunk-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'trunk'],
        minzoom: 8,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#e0c080',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            8,
            1,
            12,
            3.5,
            16,
            7,
            18,
            10,
          ],
          'line-gap-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            8,
            0.5,
            12,
            2.5,
            16,
            5,
            18,
            7,
          ],
        },
      },
      {
        id: 'road-motorway',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'motorway'],
        minzoom: 6,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#ffe6b3',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            6,
            0.5,
            10,
            2,
            14,
            5,
            18,
            8,
          ],
        },
      },
      {
        id: 'road-motorway-casing',
        type: 'line',
        source: 'openmaptiles',
        'source-layer': 'transportation',
        filter: ['==', 'class', 'motorway'],
        minzoom: 6,
        layout: {
          'line-cap': 'round',
          'line-join': 'round',
        },
        paint: {
          'line-color': '#d99b4e',
          'line-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            6,
            1,
            10,
            3,
            14,
            7,
            18,
            11,
          ],
          'line-gap-width': [
            'interpolate',
            ['exponential', 1.5],
            ['zoom'],
            6,
            0.5,
            10,
            2,
            14,
            5,
            18,
            8,
          ],
        },
      },
      {
        id: 'place-label',
        type: 'symbol',
        source: 'openmaptiles',
        'source-layer': 'place',
        minzoom: 6,
        layout: {
          'text-field': ['get', 'name'],
          'text-size': [
            'interpolate',
            ['linear'],
            ['zoom'],
            6,
            ['match', ['get', 'class'], 'city', 12, 10],
            12,
            ['match', ['get', 'class'], 'city', 16, 'town', 14, 12],
            16,
            ['match', ['get', 'class'], 'city', 20, 'town', 16, 14],
          ],
          'text-anchor': 'center',
          'text-offset': [0, 0.2],
        },
        paint: {
          'text-color': '#2d2d2d',
          'text-halo-color': '#ffffff',
          'text-halo-width': 1.5,
        },
      },
    ],
  };
}
